apiVersion: apps/v1
kind: Deployment
metadata:
  name: vishnu-vk
  labels:
    app: django-blog

spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-blog
  template:
    metadata:
      labels:
        app: django-blog
    spec:
      containers:
      - name: vishnu-vk
        image: visnu56/dockerimages:1
        ports:
        - containerPort: 8000